version: '3.8'

networks:
  mynet:
    driver: bridge

volumes:
  db_data:

services:

  query-service:
    image: ion21/query-service:v2
    networks:
      - mynet
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
#
#      SPRING_APPLICATION_NAME: query
#      APPLICATION_JWT_SECRETKEY: asdasdasdasdasd123344asdasdasdasdasasd12321332sadas
#      APPLICATION_JWT_TOKENPREFIX: Bearer
#      APPLICATION_JWT_TOKENEXPIRATIONAFTERDAYS: "7"
