spring:
  datasource:
    url: jdbc:mysql://78.96.25.131:3306/test_db?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: R@0t
    driver-class-name: com.mysql.cj.jdbc.Driver

